### ISSUE TITLE
Hi, can you provide your local rotation code?

### ISSUE THREAD

**Issue by liudaizong** [Hezhicao/LFnet#1]

**Comment by HezhiCao** [comment]
Sorry for being late, I will update the code within this month.

**Comment by HezhiCao** [comment]
@liudaizong The code has been updated. Hope it will help. The original version has been missed and I rebuilt it recently.  However, this version seems to be prone to overfit than before and I have not solved it. But we still obtained 90.55% during training and 91.08% by voting in the classification task.  Note that **_p_i_** has not been normalized as in our paper. The performance of the segmentation model was left for future tests. Thanks for your attention.
